quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_USER}:${DB_PORT}/${DB_NAME}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.jdbc.max-size=20

quarkus.hibernate-orm.log.sql=false